# Generated by Django 4.2.23 on 2025-08-07 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Admin',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='descrição')),
                ('size', models.CharField(max_length=10, verbose_name='tamanho')),
                ('color', models.CharField(max_length=20, verbose_name='cor')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managment.admin', verbose_name='autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managment.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Roupas',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='https://cdn3.iconfinder.com/data/icons/fashion-16/1000/fashion_dress-1024.png')),
                ('clothing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='managment.clothing', verbose_name='roupa')),
            ],
            options={
                'verbose_name': 'Imagens',
                'ordering': ['image_url'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('phone', models.CharField(max_length=15, verbose_name='telefone')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['name'],
            },
        ),
    ]
